version: '2'
catalog:
  name: "Printerscript"
  version: "0.0.1"
  description: "MicroService for remote printing from chalmers.it"
  minimum_rancher_version: v0.46.0
services:
  proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        frontend 80
          redirect prefix https://chalmers.it/print code 301 if { path -i / }

        backend printing_bk
            compression algo gzip
            compression type text/html text/plain text/css application/json
      port_rules:
      - backend_name: printing_bk
        hostname: ''
        path: /
        priority: 1
        protocol: http
        service: printerscript
        source_port: 80
        target_port: 3000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  database:
    scale: 1
    start_on_create: true
  printerscript:
    scale: 1
    start_on_create: true
